
// Catalogue
export enum CustomerType {
  PARTICULIER = 'PARTICULIER',
  AGENT_COMMERCIAL = 'AGENT_COMMERCIAL',
  REVENDEUR = 'REVENDEUR',
}

export enum DocumentType {
  MANUAL = 'MANUAL',
  DATASHEET = 'DATASHEET',
  WARRANTY = 'WARRANTY',
  CERTIFICATE = 'CERTIFICATE',
  OTHER = 'OTHER',
}

export enum StockMovementType {
  ENTREE = 'ENTREE',
  SORTIE = 'SORTIE',
  AJUSTEMENT = 'AJUSTEMENT',
  RETOUR = 'RETOUR',
  RESERVATION = 'RESERVATION',
  LIBERATION = 'LIBERATION',
}

export enum PriceType {
  BASE = 'BASE',
  WHOLESALE = 'WHOLESALE',
  PROMO = 'PROMO',
}

// Commandes
export enum OrderStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  PAID = 'PAID',
  PREPARING = 'PREPARING',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum OrderType {
  SALE_ONLY = 'SALE_ONLY',
  INSTALLATION_ONLY = 'INSTALLATION_ONLY',
  SALE_AND_INSTALLATION = 'SALE_AND_INSTALLATION',
}

export enum QuoteStatus {
  PENDING = 'PENDING',
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum ServiceType {
  ELECTRICAL_INSTALLATION = 'ELECTRICAL_INSTALLATION',
  SECURITY_INSTALLATION = 'SECURITY_INSTALLATION',
  MAINTENANCE = 'MAINTENANCE',
  CONSULTATION = 'CONSULTATION',
  CUSTOM = 'CUSTOM',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  PAID = 'PAID',
  REFUNDED = 'REFUNDED',
  FAILED = 'FAILED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  MOBILE_MONEY = 'MOBILE_MONEY',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CARD = 'CARD',
  ON_DELIVERY = 'ON_DELIVERY',
}

export enum DeliveryMethod {
  PICKUP = 'PICKUP',
  HOME_DELIVERY = 'HOME_DELIVERY',
  DROPSHIP = 'DROPSHIP',
}